name: Action CI

on:
  pull_request:
    branches: [ main ]

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup and run tests
        working-directory: ./gig-microservice1
        run: |
          npm ci
          npm run build --if-present
          npm test
