name: Action CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  microservice1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup and run tests Microservice 1
        working-directory: ./gig-microservice1
        run: |
          npm ci
          npm run build --if-present
          npm test

  microservice2: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup and run tests Microservice 2
        working-directory: ./gig-microservice2
        run: |
          npm ci
          npm run build --if-present
          npm test
